FROM ndt/host:focal
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    net-tools iproute2 iputils-ping iperf3 tcpdump ethtool \
 && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
