FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    net-tools iproute2 iputils-ping iperf3 tcpdump ethtool \
 && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
